### ISSUE TITLE
i Can't run app.

### ISSUE THREAD

**Issue by toan12520447** [phuockv/CallVideoOneToOne#1]
Hi, my name is Toan. I am a learner iOS. I can't run this app now. Please tell me how can i run this app ?
Many thanks!

**Comment by phuockv** [comment]
Hi @toan12520447 . 
Thank you for your question. This app is just to demo video call. You need access token to demo it
Don't focus much on this app because just my demo.

**Comment by toan12520447** [comment]
Ok. Many thanks!
